### ISSUE TITLE
Skills appearing twice in upgrade list?

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#112]
![screenshot 2016-04-06 at 19 02 10](https://cloud.githubusercontent.com/assets/13360859/14308436/3ad8ec2e-fc2a-11e5-898d-cde2b38994d8.png)

See screenshot - replicates all skills in each category - but not stats - when seelcting skill pick

**Comment by hutchinsfairy** [comment]
I saw this on our local league. We haven't looked into at all really as it's harmless but just to confirm that it's not just you!

**Comment by Shteve0** [comment]
Ha, thanks Tom.  Just logged in to thenadev and it's repeating on a skaven
team in KRBBL too.

Right, so we have a confirmed bug.  Now to track it down!

**Comment by rythos42** [comment]
The problem is that as part of the mobile stuff, I called `Player->setChoosableSkills()` on construction, instead of waiting until the data was needed (as had been done before). This method was called again in `class_team_htmlout` line 401 just before outputting a list of skills a player could choose from, and the method doesn't account for duplicates.

The solution here was to remove the second call inside `class_team_htmlout`, but this could show up in other places. There is one call to `setChoosableSkills` that I couldn't trace it's path, inside `Player->addSkill()`. This method is used twice in `class_team_htmlout`, looks like when adding skills from the commish interface there. I tried using it and didn't see any problems, but maybe you guys will see something I missed!
