### ISSUE TITLE
Set "Tie teams to divisions" to off by default

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#114]
The "new league" documentation says to uncheck this because it's not useful for multi-season leagues. May as well make it off by default.

**Comment by hutchinsfairy** [comment]
Is there a broader question of what this option is there for? I know from experience that it causes problems if it is initially checked and you change your mind. Personally I would bury or remove the option but I don't know how other people might be using it.

**Comment by rythos42** [comment]
Yeah, I'm not certain i see the point of it. But I've only been a coach in 1 league with 2 seasons so I'm not always aware of the finer points of the system. :)

**Comment by hutchinsfairy** [comment]
I've just been refreshing my memory about the problems I had with this. Unless it has changed since, I think this ties the team to a division on team creation. There was then no way I could find to "untie" that team apart from in the database. Even unchecking the box only seemed to affect subsequent new teams.

Using the new troubleshooting [page ](http://thenafdev.obblm.com/troubleshoot.php) (thanks!) on naflm shows 3/33 leagues with the ties turned on so I guess they could be asked?

Perhaps worth revisiting down the road. changing the default should work for all but the incurably curious.
