### ISSUE TITLE
Add Username in to Request League option

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#124]
When leagues are set up they need a commish - at the momemt there needs to be an email exchange between admin and commish to establish user account.

Can we add a Username field and an explanation that the account should be set up (but does not need to be approved) before the league can be set up?

**Comment by rythos42** [comment]
The username field is written to the e-mail as a "hidden" input. I've been meaning to look into how Novarea managed to send the request _without_ a username, because he hadn't created a OBBLM account at all and the Request button shouldn't be visible unless you're logged in.

The explanation is new, and possible yeah.

**Comment by rythos42** [comment]
I think I see what happened here. The link to the "request a league" page isn't visible on the menu unless you're logged in, which means you need to have an account.

But someone sent the link `http://thenafdev.obblm.com/handler.php?type=registration` to Novarea, which bypasses the hidden link.

I added a check at the top of the request-league page that directs the user to register first if they aren't logged in.
