### ISSUE TITLE
Announcements aren't appearing

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#14]
Announcements on front page are failing to appear - request succeeds but the box is non existent

**Comment by williamleonard** [comment]
Can you give an example page?

**Comment by Shteve0** [comment]
Sure - just the main index.  http://thenafdev.obblm.com/index.php?section=main

I create an announcement, post it, and get the message back "request succeeded" but no message appears.  Baffled.

**Comment by Shteve0** [comment]
I wonder if this is related to the league manager issue?  Both perform checks to isLocalCommish.  Neither appears to be a skinning issue.  I've gone through every file I've changed line by line... I wonder if a parameter is being redefined in one of the introduced modules?  I'm not sure what else it could be...

**Comment by rythos42** [comment]
Where in the UI do you create an announcement?

**Comment by Shteve0** [comment]
Log in as an admin or commissioner; then it's on the index page, under the
intro

**Comment by Shteve0** [comment]
"New Message"

**Comment by rythos42** [comment]
Great, found it.

After a bit of searching, this is an easy solution...but I don't see how anyone other than the primary developer would have known how to fix it without digging. :(

The problem is that the table "texts" should have a column "pinned", but it doesn't. The SQL in class_text.php, line 277 is trying to order by pinned, but it doesn't exist. 

The solution is to run `upgrade.php` on the server from your browser. I ran it on my local copy, and selected "0.96 to 0.97" and it works. It doesn't _look_ like any of the other upgrades need to be run.

**Comment by Shteve0** [comment]
LEGEND.

So now the dev page is swamped by my gibberish tests.  Massive relief.  Thank you Craig!  Huge weight off :)

**Comment by rythos42** [comment]
Yes, it's definitely best not to LOSE functionality when trying to upgrade! :D Happy to help!
