### ISSUE TITLE
Request: method of permalinking to league home

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#16]
Can we permalinking to a league's landing page when multiple leagues share a database? For example, thenaf.obblm.com plays host to a number of leagues - an index.php style, permalinked page for each would allow me to cut the league selection box and restructure the home menu to a region > country > league format.

Any ideas welcomed!

**Comment by mfranchetti** [comment]
I can think of a couple of ways to do it:
* Move the LeagueID from a $_POST variable to $_GET variable. This would then
mean that a URL of thenaf.obblm.com/index.php?lid=5 would link directly to the
league with ID of 5.
o Pros: Fairly straight forward fix (I think). Will need to update header.php
and index.php, Allows direct linking.
o Cons: Ugly links, not easy remembered or passed on
* Update the league creation process to add a subfolder to the main directory
with the same name. Inside this folder is a simple index.php file which
redirects to the main index.php file with a $_POST value for the league. This
would allow use of thenaf.obblm.net/wbbl/ to link directly to the WBBL page
o Pros: Nicer URLs created, easier to promote.
o Cons: More work required to setup. URL after redirect will revert to
thenaf.obblm.net, so won't be possible to copy and past current address to
perma-link. (There should be ways around this, but I'll need to give it more
thought) Leagues will require unique names (We can make the URL extension a
separate value from the league name so that only the URL bit has to be unique)

Thoughts?

?space?--On 23 September 2015 at 00:08 Shteve0 <notifications@github.com> wrote:


Can we permalinking to a league's landing page when multiple leagues share a
database? For example, thenaf.obblm.com plays host to a number of leagues - an
index.php style, permalinked page for each would allow me to cut the league
selection box and restructure the home menu to a region > country > league
format.

Any ideas welcomed!

—
Reply to this email directly or view it on GitHub
<https://github.com/TheNAF/naflm/issues/16> .

**Comment by williamleonard** [comment]
This is similar to what I suggested, though I wouldn't change it, I would add it as functionality.  You can do it as a REQUEST or just a separate piece of code that checks it as a GET only.  Once you are in the site with that link, it remembers it as a session so not every link on a page has to be redone.  Each page could have the permalink somewhere easy to copy or email to someone though.  I know it may seem easy to fully switch everything over that way, but I really would like to ensure changes don't break any compatibility.

Since the league name is in the LEAGUES table along with the id, you could allow the league selection GET variable to be a name as well and do a query on the database to get the number in the background.

As for it using a directory as the selector, I think that should be a rewrite rule in .htaccess and not be coded.  Example: thenaf.obblm.net/wbbl/ redirects to http://www.thenaf.obblm.com/index.php?slid=wbbl and in the background that sets the session for the id of wbbl.  If you were at http://www.thenaf.obblm.com/index.php?section=coachlist maybe they enter http://www.thenaf.obblm.com/wbbl/index.php?section=coachlist and it rewrites to http://www.thenaf.obblm.com/index.php?section=coachlist&slid=wbbl.

**Comment by mfranchetti** [comment]
Agree, rewrite rule in .htaccess would be the way to go. I suspected that was
doable but had to go and read up on it before saying anything. :)

**Comment by Shteve0** [comment]
Excellent work chaps.  Any volunteers willing to have a go at this?  Note that it's possible that several leagues will have the same names - as demonstrated by the fact that mfranchetti and I both run leagues called WBBL on different sides of the planet.

Just to be clear I'm thinking I'll replace the Home button in the menu with:

Leagues
   > My League (if logged in only, to be set in preferences)
   > North America
        >  Canada
                > CHOP
                > KBBL
   > Europe
        >  UK
                > Exiles
                > ARBBL
                > WBBL (UK)    
   > Australasia
        >  New Zealand
               > ChriBBL
               > WBBL (NZ)

Which should make tracking leagues down slightly easier.

**Comment by Shteve0** [comment]
Will the solution(s) proposed remember the selection as the site is navigated? Ie when looking at league tables, and so on, can we keep the skin associated with the league in place?

**Comment by williamleonard** [comment]
Yes.  The GET would trigger the same thing that the selection combo box would and keep that in the $SESSION.

Here is the code that sets the session for the league id: https://github.com/TheNAF/naflm/blob/master/lib/class_htmlout.php#L542

**Comment by williamleonard** [comment]
I just tested this change:

    /* Simple league selector (SLS) */ 
547     $lids = array_keys($leagues); 
548     if (isset($_REQUEST['SLS_lid']) && in_array($_REQUEST['SLS_lid'], $lids)) { 
549         $_SESSION[self::T_NSStr__node]    = T_NODE_LEAGUE; 
550         $_SESSION[self::T_NSStr__node_id] = (int) $_REQUEST['SLS_lid']; 
551     } 

And then I added &SLS_lid=1 to the end of a URL and it brought me back to league 1.  I also tried &SLS_lid=2 and that did nothing since 2 didn't exist.  But then I tried &SLS_lid=3 and that brought me to the third league and kept me there when browsing.

Similarly, that area could call a function to match up a name and maybe be redone to allow the GET to be lid or something similar.  But this will let you test with the basic premise of it.

**Comment by Shteve0** [comment]
This is brilliant.  Works like a charm!  Thanks man :)

http://thenafdev.obblm.com/index.php?SLS_lid=1
http://thenafdev.obblm.com/index.php?SLS_lid=2

**Comment by Shteve0** [comment]
c03d2fac0146529fcfe35cfdc9f08cbd6e1dd1d5

**Comment by Shteve0** [comment]
Cool, started reworking the menu. Under Home I'll be adding a separate link to each league, using this method (and worry about translations later). If anyone knows how I'd go about calling the league name for league id = 1, for example, that would be appreciated!

**Comment by Shteve0** [comment]
Demo of the home linking now up on the dev site. Will also be moving the other menus round, will do a commit when that's finished
