### ISSUE TITLE
League Preferences--League rules not updating

### ISSUE THREAD

**Issue by fejwe** [TheNAF/naflm#203]
Good afternoon all, new here, hopefully I'm giving the right info.

URL: http://motorcitybloodbowl.org/

I've updated the League Rules in the Preferences window, but they're not updating on http://motorcitybloodbowl.org/index.php?section=rules. I ran the Database Maintenance and Database Synchronization steps, but that didn't cause the rules to show up.

Thanks in advance for any help
Tom

**Comment by fejwe** [comment]
On investigating more: It looks like the Welcome message isn't updating either. I'm wondering if this is at all connected to the fact that I previously included the rules and welcome in the original settings.php. I'm wondering what would happen if i went into the original settings.php file and removed the originally authored content, but looking at the "settings_none.php" I'm not sure how to do that.

**Comment by fejwe** [comment]
I just tried to update the available teams via the settings.php file with no luck. I also tried to alter the ranking systems, but that also didn't work. It seems to me like everything is still pointing to old versions of the settings.php file. I've been able to alter the copy of the site description by manually changing the settings.php file but not by using the preferences.

**Comment by Shteve0** [comment]
Hi fejwe

You dont appear to be running naflm, or at least you've missed some files
(like the local_settings files you need to call the league prefs settings).

Note that the github repo is not for tech support, can I ask you to try tff
or the endzone please? Pm me at Shteve0 on either site and I'll work with
you on it.

On 2/03/2017 9:37 AM, "fejwe" <notifications@github.com> wrote:

I just tried to update the available teams via the settings.php file with
no luck. I also tried to alter the ranking systems, but that also didn't
work. It seems to me like everything is still pointing to old versions of
the settings.php file. I've been able to alter the copy of the site
description by manually changing the settings.php file but not by using the
preferences.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheNAF/naflm/issues/203#issuecomment-283462288>, or mute
the thread

**Comment by fejwe** [comment]
Absolutely. My sincerest apologies for the incorrect direction/forum/etc. I was under the impression I had been upgraded by the ISP but apparently didn't understand everything completely. 

Please feel free to delete all my comments, and I'll address them to a more correct place.

Sorry!

**Comment by fejwe** [comment]
Sorry, reopening after discussions with my ISP, who performed the upgrade and suggested I reopen this bug. 
Having updated to the revised settings files, I'm still experiencing issues with the league preferences.

**Comment by williamleonard** [comment]
Actually can you try it again.  I found a problem with the file permissions from how I copy the files for the upgrade.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Shteve0** [comment]
Hi, this has been dormant for a while and appears to be a service request rather than a bug with the software.  If your problem persists please use the new helpdesk at http://theendzone.co/groups2/89-obblm
