### ISSUE TITLE
PDF generation - wizards

### ISSUE THREAD

**Issue by Hjelmen** [TheNAF/naflm#225]
Hi all!

My users reported that the PDF rosters does not work. I've applied the fix in #159, which solves the issue with ob_clean().

But another issue is still causing me some problems:

![image](https://user-images.githubusercontent.com/29941906/30284179-76f28ba2-971a-11e7-9dda-360c847177af.png)

I can see that the Wizard element of the Inducements array is not correct/present, but I can't find which code where the Inducements array is populated.

I can change some code myself, but could one of you help me out with where to change?

Thank you :)

**Comment by mfranchetti** [comment]
Can you confirm the steps to reproduce this issue please? Is this generating a PDF Roster from the Inducements Try-Out page, after adding a Wizard?
I cannot reproduce the issue on the current NAFLM install.
What changes have been made to your install?

**Comment by Hjelmen** [comment]
Go to a team > go to roster > click PDF
![image](https://user-images.githubusercontent.com/29941906/36627924-6a991e7c-194a-11e8-930f-a0e1a05fe696.png)

The only change I've applied is to add the fix in https://github.com/TheNAF/naflm/issues/159

**Comment by thefloppy1** [comment]
Can I ask how your players are selecting a wizard for the team?

**Comment by Hjelmen** [comment]
This is the inducements try-out we have on our site:

![image](https://user-images.githubusercontent.com/29941906/37612905-cf4e7344-2ba6-11e8-8760-c5a13b7bcf46.png)

Seems like we're using another set up (new BB rules?) that doesn't include wizards.

**Comment by thefloppy1** [comment]
Horatio X is the wizard.  He only costs 80K and if both of you choose him
he doesn't turn up, but takes both your money.

**Comment by Hjelmen** [comment]
Ok. But isn't that just a work around? How would I go about solving the crash?

**Comment by mfranchetti** [comment]
The Inducements array is populated by the game_data file, there's a few versions depending on which ruleset you're using. It looks as if the Wizard entry has been removed from your file (I assume to comply with BB2016 rules) but this is causing an error for the PDF generator as it expects a Wizard value to be passed.
This has recently been updated in the code so you could try updating your files or if you want to be specific only:
    \header.php
    \lib\game_data_bb2016.php
    \modules\inducements\class_inducements.php

That will restore the wizard and will rectify the issue. However, if you do not want the wizard, you could change his cost to 0 in the game_data file. The Inducements module has been modified so that it will not display any zero cost inducements but should not impact the PDF generation.
I've tested this on my dev site and it seems ok.

**Comment by Hjelmen** [comment]
Seems like it has been fixed in the SPIKE beta update. Thank you for your help! :)
