### ISSUE TITLE
Remove obsolete/optional stats

### ISSUE THREAD

**Issue by Hawke** [TheNAF/naflm#237]
Current blood bowl rules don’t use “Gate” or “Fans” in the way that it appears OBBLM was designed for.

There’s also no relevant distinction between “Badly Hurt”, “Serious Injury” or “Killed”: They’re all just “Casualty”, worth 2 SPP each.

And “Aging”/retirement doesn’t work the same way in current editions.

Would be nice to see that updated to follow current game rules.

**Comment by thefloppy1** [comment]
While yes you get 2 SSP for a Cas, the SI is very much needed, as is the Kill.  You can rank teams by CAS then by Kills if you wish, or even players.  
SI is very important in the game, it is used all the time, Badly Hurt you are out for the rest of the game.  
SI you are out for this game and the next, plus you either get a Niggle or a stat decrease, all of which are tracked and attached to the SI.  
Ageing is used in some leagues.

Fans is used the way the rules are written, how else do you get FAME.  Gate is just the addition of the two teams fans.  This is a statistical entry, nothing more.

**Comment by Hawke** [comment]
Agreed that SI and BH are important to record for injuries, but not for injuries *caused*.

Sure you can rank by kills if you wish but you could also rank by … I dunno, successful handoffs or rushing distance or really any stat you cared to track. Why treat Kills specially in this regard?

If it’s “used in some leagues” (aging, scoring by kills, etc.) surely it would be better made league-optional rather than required for leagues that don’t care about it.

As for Gate it seems to be a holdover from 4th edition, not really relevant for a long time. Personally I’d rather record exactly what the procedure says: a separate fan count for each team. From that, FAME can be automatically calculated (and gate count for statistical purposes). If gate is just the total of the fans, what’s “Fans (RL Spectators)”?

**Comment by thefloppy1** [comment]
RL Spectators = Peanut gallery.  Real Life people watching the game.

**Comment by Hawke** [comment]
Oof. Well, that should probably be clarified somewhere.

**Comment by thefloppy1** [comment]
again it is the admin doc, written a couple of years ago. What leagues choose to use as tie breakers is up to them, my league uses Kills.

**Comment by Hawke** [comment]
That particular item does not seem to be in the admin doc, including in the glossary on page 71:
https://www.thenaf.net/wp-content/uploads/2016/06/NAF-OBBLM-ADMIN-GUIDE.pdf

I understand that leagues could use anything as tie breakers, my point is that in that case it should be made optional to the league rather than an irrelevant fact of life to most leagues, i.e. it would be fine as the "inflicted_kills" extra stat. Maybe allow leagues to move any "extra stat" they want to the main page or something.

**Comment by thefloppy1** [comment]
sorry yes, not all in the same place. I keep forgetting, been a while since I did a config of a league.
House ranking system Page 12.  - Create the rules for what you want to rank anything by, then once the league is being setup you can choose what ranking rule set to use.

The local settings file  settings_#.php where the # is the league ID, you can create custom tables that are displayed on the front page this section should be in the advanced settings page around 64 ish.. 

In my league we have a table for latest skilled player, latest dead player, and most kills. as well as the silver and gold league rankings tables. 
we also have tables for the recently played games, and upcoming games. 

Also of note, I play in two leagues, one I do the admin work in OBBLM for, the other uses a different system, I am only a player.  Both use Kills as a tie breaker.

**Comment by mfranchetti** [comment]
The stats need to remain in order to maintain compatability with FUMBBL and Cyanide. Additionally, some leagues and coaches like to track the extra fluff that goes with specific types of Casualties.
I think the Match Report screen could be improved and streamlined to hide some of the fields until they are required.
