### ISSUE TITLE
Wanted / Famous plugins needs admin not commish

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#48]
When commissioners access the Wanted, Prizes, Hall of Fame and Famous Teams plugins they see no option for adding new entries to their league; only admins have the permission. Assume were calling the wrong canedit?

**Comment by Shteve0** [comment]
This is still an in demand issue.

If anyone has any ideas, please shout out!

**Comment by thefloppy1** [comment]
I feel the problem is in this function; makeList($ALLOW_EDIT)
Does not seem to set the coach to allow_edit even though it is being called before, "New" should be drawn on the screen.

**Comment by rythos42** [comment]
As thefloppy1 said, the $ALLOW_EDIT was only checking against GLOBAL_ADMIN in handler.php.

It took me a while to figure out how to tell if a user had permission for a particular "thing" (league, tournament, etc). I moved the permission check from handler.php into each of the modules. The modules should be in charge of their own permissions, rather than letting the abstract module handler figure it out for them.
